var json_TitikRs20182020_3 = {
"type": "FeatureCollection",
"name": "TitikRs20182020_3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Nama": "RSU Banyumanik", "Alamat": "Jl. Perintis Kemerdekaan No.57, Banyumanik, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50265", "N0.Tlp": "081234563763", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4164133, -7.061514345 ] } },
{ "type": "Feature", "properties": { "Nama": "IGD RS Elisabeth", "Alamat": "XCR9+QHC, Tegalsari, Kec. Candisari, Kota Semarang, Jawa Tengah 50614", "N0.Tlp": "08977665545", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4188788, -7.00794409 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Pantiwilasa", "Alamat": "Jalan Dokter Cipto No.50, Bugangan, Kec. Semarang Tim., Kota Semarang, Jawa Tengah 50123", "N0.Tlp": "089776652322", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.434417, -6.972860262 ] } },
{ "type": "Feature", "properties": { "Nama": "RSIA Kusuma", "Alamat": "Jl. Bugangan No.3-5, Rejosari, Kec. Semarang Tim., Kota Semarang, Jawa Tengah 50126", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4357886, -6.974087202 ] } },
{ "type": "Feature", "properties": { "Nama": "Siloam Hospital Smg", "Alamat": "Jl. Kompol Maksum No.296, Peterongan, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50242", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4341578, -6.996919076 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Roemani", "Alamat": "Jl. Wonodri Baru Raya No.22, Wonodri, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50242", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4278385, -7.000434104 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Kariadi", "Alamat": "Jl. DR. Sutomo No.16, Randusari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50244", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4074832, -6.994119178 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Telogorejo", "Alamat": "Jl. Kh Ahmad Dahlan, Pekunden, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50134", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4271368, -6.987270496 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Bhayangkara", "Alamat": "Jalan Sultan Agung, No. 131, Komplek Akademi Kepolisian Candi Baru, Gajahmungkur, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50232", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.40976, -7.016399251 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Umum William", "Alamat": "Jl. Letnan Jenderal S. Parman No.5, Petompon, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50237", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4051143, -6.996633601 ] } },
{ "type": "Feature", "properties": { "Nama": "RSBhayangkara smg", "Alamat": "Jl. Majapahit No.140, Gayamsari, Kec. Gayamsari, Kota Semarang, Jawa Tengah 50248", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4462355, -7.000088762 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Amino", "Alamat": "Jl. Brigjen Sudiarto No.347, Gemah, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50611", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4628048, -7.007423773 ] } },
{ "type": "Feature", "properties": { "Nama": "RS DIPENOGORO", "Alamat": "Jl. Prof. Sudarto SH, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4434884, -7.047105767 ] } },
{ "type": "Feature", "properties": { "Nama": "RS KRMT", "Alamat": "Jl. Fatmawati No.1, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4660765, -7.03197794 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Permata Medika", "Alamat": "Jl. Raya Mr. Moch Ichsan No.93-97, Ngaliyan, Kec. Ngaliyan, Kota Semarang, Jawa Tengah 50181", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.3403076, -6.990821209 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Columbia Asia", "Alamat": "Jl. Siliwangi No.143, Kalibanteng Kulon, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50145", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.3825413, -6.982197541 ] } },
{ "type": "Feature", "properties": { "Nama": "RS Sultan Agung", "Alamat": "Jl. Kaligawe Raya No.KM. 4, Terboyo Kulon, Kec. Genuk, Kota Semarang, Jawa Tengah 50112", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4620634, -6.947905636 ] } },
{ "type": "Feature", "properties": { "Nama": "RSU Cepoko", "Alamat": "W9M5+6CW, Cepoko, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50222", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.3566843, -7.056495788 ] } },
{ "type": "Feature", "properties": { "Nama": "UGD RSND", "Alamat": "XC2V+WP4, Jl. Prof. Sudarto, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275", "N0.Tlp": "08977665554", "Fasilitas": "Rawat Jalan,\nUnit Gawat Darurat,\nRawat Inap,\nICU,\nKamar Operasi,\nMedical Check Up,\nFarmasi,\nAmbulance,\nFisioterapi,\nLaboratorium,\nRadiologi (USG,Dental X-Ray),\nDrill Evacuation" }, "geometry": { "type": "Point", "coordinates": [ 110.4442989, -7.047558722 ] } }
]
}
